package base;

public enum ErrorCode  {

    SUCCESS("SUCCESS", "成功！"),
    BUSINESS_PARAMETERS_FAULT("BUSINESS_PARAMETERS_FAULT", "参数业务失败"),
    BUSINESS_NOT_EMPTY("BUSINESS_PARAMETERS_FAULT", "参数不能为空字符串"),
    BUSINESS_DEAL_FAULT("BUSINESS_DEAL_FAULT", "业务处理失败"),
    REMOTE_SERVER_FAULT("REMOTE_SERVER_FAULT","远程调用失败"),
    INVALID_LOGIN_USERNAME("USERNAME_NOT_NULL", "用户名不能为空"),
    INVALID_LOGIN_USEREXIST("INVALID_LOGIN_USEREXIST", "手机号已经存在"),
    CAPTCHA_CODE_WRONG("CAPTCHA_CODE_WRONG", "验证码错误"),
    INVALID_PHONE("INVALID_PHONE", "手机号格式不正确"),
    INVALID_HANDLE_SETTING("INVALID_HANDLE_SETTING", "策略接收者设置失败"),
    MYSQL_SAVE_EXCEPTION("MYSQL_SAVE_EXCEPTION", "MySQL保存异常"),
    MYSQL_SELECT_EXCEPTION("MYSQL_SELECT_EXCEPTION", "MySQL未查询到数据"),
    MYSQL_UPDATE_EXCEPTION("MYSQL_UPDATE_EXCEPTION", "MYSQL更新异常"),
    CAPTCHA_INVALID_EXCEPTION("CAPTCHA_INVALID", "验证码无效"),
    CAPTCHA_TIMEOUT_EXCEPTION("CAPTCHA_TIMEOUT", "验证码超时"),
    PHONE_EXIST("PHONE_EXIST", "手机号已存在"),
    EMAIL_EXIST("EMAIL_EXIST", "邮箱已存在"),
    NICK_EXIST("NICK_EXIST", "用户名已存在"),

    USER_NOT_EXIST("USER_NOT_EXIST", "用户不存在"),
    USER_NOT_LOGIN("USER_NOT_LOGIN", "用户未登录"),
    GOTONE_SMS_SEND_EXCEPTION("GOTONE_SMS_SEND_EXCEPTION", "沟通平台短息发送异常"),
    GOTONE_EMAIL_SEND_EXCEPTION("GOTONE_SMS_SEND_EXCEPTION", "沟通平台邮件发送异常"),
    INVALID_RULE_TYPE("INVALID_RULE_TYPE", "非法的权限规则类型"),

    // checkLogin使用
    CHECK_LOGIN_NOT_FOUND("CHECK_LOGIN_NOT_FOUND", "没有找到登录信息"),

    // Update 第三方关系用
    INVALID_THRID_PARTY_PPID_BIND("INVALID_THRID_PARTY_BIND", "账号已经绑定第三方了"),
    INVALID_THRID_PARTY_UNIONID_BIND("INVALID_THRID_PARTY_BIND", "第三方账号已经绑定其他用户了"),
    INVALID_THRID_PARTY_RELATION("INVALID_THRID_PARTY_RELATION", "找不到账号绑定关系"),
    ;

    private String code;
    private String msg;

    private ErrorCode(String code, String msg) {
        this.code = code;
        this.msg = msg;
    }

}

